// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnsqavSonzNjd-n70p8GF6sZRdvwy8SpI',
    appId: '1:209167769198:web:764655945e40798b46907f',
    messagingSenderId: '209167769198',
    projectId: 'mod-12-23da1',
    authDomain: 'mod-12-23da1.firebaseapp.com',
    storageBucket: 'mod-12-23da1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6w0Yccl4F97ZNXV7XrunFi9uA-rOq174',
    appId: '1:209167769198:android:23740b58bd96948b46907f',
    messagingSenderId: '209167769198',
    projectId: 'mod-12-23da1',
    storageBucket: 'mod-12-23da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrIBOCE_W8a5GJnv8ZcehLFS_rebfHgM',
    appId: '1:209167769198:ios:fa3bb9aa6321071e46907f',
    messagingSenderId: '209167769198',
    projectId: 'mod-12-23da1',
    storageBucket: 'mod-12-23da1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrIBOCE_W8a5GJnv8ZcehLFS_rebfHgM',
    appId: '1:209167769198:ios:fa3bb9aa6321071e46907f',
    messagingSenderId: '209167769198',
    projectId: 'mod-12-23da1',
    storageBucket: 'mod-12-23da1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnsqavSonzNjd-n70p8GF6sZRdvwy8SpI',
    appId: '1:209167769198:web:8ebdbc8c640d3d9046907f',
    messagingSenderId: '209167769198',
    projectId: 'mod-12-23da1',
    authDomain: 'mod-12-23da1.firebaseapp.com',
    storageBucket: 'mod-12-23da1.firebasestorage.app',
  );
}
